spring:
  application:
    name: HealthSphere_Backend
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/healthsphere
    username: 1olelllka
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
server:
  port: 8000