spring:
  application:
    name: HealthSphere_Backend
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/healthsphere
    username: 1olelllka
    password: secret
server:
  host: 8000
