spring:
  application:
    name: HealthSphere_Backend
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/healthsphere
    username: 1olelllka
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: http://localhost:9200
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
  api-docs:
    enabled: true

server:
  port: 8000

management:
  endpoints:
      web:
        cors:
          allowed-origins: http://localhost:5173
          allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
          allow-credentials: true
springdoc:
  show-actuator: true