version: '3.9'
name: 'health-sphere-backend-development'
services:
  elasticsearch:
    image: 'elasticsearch:7.17.23'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'http.cors.enabled=true'
      - 'http.cors.allow-origin=http://localhost:8080'
      - 'http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - '~/apps/elasticsearch:/var/lib/elasticsearch/'
  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=healthsphere'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=1olelllka'
    ports:
      - '5432:5432'
    volumes:
      - '~/apps/postgres:/var/lib/postgresql/data'
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - '~/apps/.redis-data:/data'
