name: CI/CD Pipeline for HealthSphere Project

on:
  push:
    branches:
      - main

jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('client/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: ./client
        run: yarn install

      # - name: Build client
      #   working-directory: ./client
      #   run: yarn build

      # - name: Upload client build artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: client-build
      #     path: ./client/dist
